name: Auto PR to main

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'

jobs:
  auto-pr-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Setup Git
        run: |
          git config --global user.name 'roadrunner-bot'
          git config --global user.email 'roadrunner.bot@swiggy.in'

      - name: Cherry-pick the merge commit
        run: |
          git checkout main
          git pull origin main
          git checkout -b auto-pr-${{ github.event.pull_request.number }}-to-main
          echo "Attempting to cherry-pick ${{ github.event.pull_request.merge_commit_sha }}"
          if git cherry-pick -S -x --mainline 1 ${{ github.event.pull_request.merge_commit_sha }}; then
            echo "🎉 No conflicts! CP was a success, PR can be automerged 🎉"
            echo "HAS_CONFLICTS=false" >> "$GITHUB_OUTPUT"
          else
            echo "😞 PR can't be automerged, there are merge conflicts in the following files:"
            git --no-pager diff --name-only --diff-filter=U
            git add .
            GIT_MERGE_AUTOEDIT=no git cherry-pick --continue
            echo "HAS_CONFLICTS=true" >> "$GITHUB_OUTPUT"
          fi
          git push origin auto-pr-${{ github.event.pull_request.number }}-to-main

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "auto-pr-${{ github.event.pull_request.number }}-to-main"
          destination_branch: "main"
          pr_title: "Auto PR to main: ${{ github.event.pull_request.title }}"
          pr_body: "Automatically created PR from PR #${{ github.event.pull_request.number }} with label."
          pr_label: 'automated-pr'
          pr_assignee: ${{ github.event.pull_request.user.login }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture Milestone ID
        if: github.event.pull_request.milestone
        run: |
          PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pr_number }}")
          curl \
            -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}" \
            -d '{"milestone": '${{ env.MILESTONE_ID }}'}'
