name: Auto PR to main

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'

jobs:
  auto-pr-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Setup Git
        run: |
          git config --global user.name 'roadrunner-bot'
          git config --global user.email 'roadrunner.bot@swiggy.in'

      - name: Cherry-pick the merge commit
        run: |
          git fetch origin main:main
          git checkout main
          NEW_BRANCH="auto-pr-${{ github.event.pull_request.number }}-to-main"
          git checkout -b $NEW_BRANCH
          git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}
          git push origin $NEW_BRANCH

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: $NEW_BRANCH
          destination_branch: "main"
          pr_title: "Auto PR to main: ${{ github.event.pull_request.title }}"
          pr_body: "Automatically created PR from PR #${{ github.event.pull_request.number }} with label."
          pr_label: 'automated-pr'
          pr_assignee: ${{ github.event.pull_request.user.login }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
